name: CI

on:
  push:  
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout proyect
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api --configuration Release -o artifacts

      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dometrain-artifact
          path: ./artifacts/